export const CHECK_NODE_STATUS_START = "CHECK_NODE_STATUS_START";
export const CHECK_NODE_STATUS_SUCCESS = "CHECK_NODE_STATUS_SUCCESS";
export const CHECK_NODE_STATUS_FAILURE = "CHECK_NODE_STATUS_FAILURE";
export const BLOCK_STATUS_LOADING = "BLOCK_STATUS_LOADING";
export const BLOCK_STATUS_SUCCESS = "BLOCK_STATUS_SUCCESS";
export const BLOCK_STATUS_ERROR = "BLOCK_STATUS_ERROR";
